before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kuu
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
checksum:
  name_template: "checksums.txt"
brews:
  - repository:
      owner: winebarrel
      name: homebrew-kuu
    homepage: https://github.com/winebarrel/kuu
    description: Remove blank lines from the beginning and end of the file. Also, make duplicate blank lines into one.
    license: MIT
    install: |
      bin.install 'kuu'
